<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Laboratory 1 - Imperial (BSIS2) </title>
</head>

<body>
    <script>
        //#1
        function isOdd(num) {
            return new Promise(function (resolve, reject) {
                if (num & 1 === 1) {
                    resolve(true)
                } else {
                    reject(false)
                }
            })
        }

        let arrNum = new Array(11, 12, 31, 40, 51007);
        console.log("****No. 1****");
        for (let i = 0; i < arrNum.length; i++) {
            isOdd(arrNum[i])
                .then(result => {
                    console.log(arrNum[i] + " isOdd")
                })
                .catch(result => {
                    //pass
                });
        }


        //#2
        function getRandomCharacter() {
            return new Promise(function (resolve, reject) {
                setTimeout(function () {
                    const randChar = String.fromCharCode(97 + (Math.floor(Math.random() * 26)));
                    resolve(randChar);
                }, 500);

            })
        }

        async function printRandChar() {
            const randChar = await getRandomCharacter()
            console.log("\n****No. 2****\n" + randChar);
        }
        printRandChar();

        //#3
        function getData(T) {
            return new Promise(function (resolve, reject) {
                setTimeout(function () {
                    const randChar = String.fromCharCode(97 + (Math.floor(Math.random() * 26)));
                    reject(randChar);
                }, T);
            })
        }

        async function printRandData(T) {
            try {
                const randData = await getData(T)
                // console.log(randData +  "oks");
            } catch (err) {
                console.log("\n****No. 3****\n" +err);
            }
        }
        printRandData(500);

        //#4
        function rejectResolve(df) {
            let p = new Promise(function (resolve, reject) {
                function helper(r) {
                    const randChar = String.fromCharCode(97 + (Math.floor(Math.random() * 26)));
                    if (r & 1 === 1) {
                        resolve(randChar);
                    } else {
                        reject(randChar);
                    }
                }
                for (let k = 1; k < 3; k++) {
                    setTimeout(()=>{helper(k + df)}, 500);
                }
            });
            return p;
        }
        async function invoker() {
            let res;
            try {
                res = await rejectResolve(0);
                console.log("\n****No. 4****\n" +res);

                res = await rejectResolve(1); 
                //I had to call it twice because even though 
                //the setTimeout was called twice in the Promise
                //the promise that will be return will only hold ONE value
                //either resolve() or reject() and not both so printing both
                //under one await call is not possible.
            } catch (x) {
                console.log(x);
            }
        }
        invoker();
    </script>
</body>

</html>
